#!/bin/bash
clear

synclist="
audio
dist
docs
pictures
projects
"

function sync_start {
  # DISPLAY=:0 notify-send -t 3000 -i emblem-ubuntuone-updating "`printf "$i" | sed -e "s/\b\(.\)/\u\1/g"`" "В процессе..."
  printf "%2s${BLB}$i${NRML}\n"
  unison $i
  if tail ~/.unison/unison.log -n1 | grep 'Synchronization complete'; then
    # DISPLAY=:0 notify-send -t 12000 -i emblem-ubuntuone-updating "`printf "$i" | sed -e "s/\b\(.\)/\u\1/g"`" "Успешно завершено";
    echo "Success."
  else 
    echo "Error."
    #DISPLAY=:0 notify-send -t 10000 -i important "`printf "$i" | sed -e "s/\b\(.\)/\u\1/g"`" "Ошибка при синхронизации\n`tail ~/.unison/unison.log -n7`";
  fi
}

DISPLAY=:0 notify-send -t 2000 -i emblem-ubuntuone-updating "Unison" "Запуск синхронизации."
printf "%1s${BOLD}Unison sync stages.${NRML}\n"
for i in $synclist
  # sync_start
  unison $i
do
done;

DISPLAY=:0 notify-send -t 2000 -i emblem-ubuntuone-updating "Unison" "Все этапы синхронизации прошли успешно."
#read w
